import React from 'react';
import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Award,
  Bike,
  Calendar,
  Camera,
  CheckCircle2,
  ChevronDown,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  Compass,
  Droplets,
  Eye,
  Footprints,
  Gauge,
  HelpCircle,
  Info,
  MapPin,
  Mountain,
  PartyPopper,
  RefreshCw,
  Search,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  SunMedium,
  Thermometer,
  Timer,
  Trophy,
  Umbrella,
  Wind,
  Zap,
} from 'lucide-react';

const ICON_MAP: Record<string, React.ElementType> = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  Award,
  Bike,
  Calendar,
  Camera,
  CheckCircle2,
  ChevronDown,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  Compass,
  Droplets,
  Eye,
  Footprints,
  Gauge,
  HelpCircle,
  Info,
  MapPin,
  Mountain,
  PartyPopper,
  RefreshCw,
  Search,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Sun,
  SunMedium,
  Thermometer,
  Timer,
  Trophy,
  Umbrella,
  Wind,
  Zap,
};

interface IconRendererProps {
  name: string;
  className?: string;
  size?: number;
}

export const IconRenderer: React.FC<IconRendererProps> = ({ name, className = '', size = 18 }) => {
  const Component = ICON_MAP[name] || HelpCircle;
  return <Component className={className} size={size} aria-hidden="true" />;
};
